# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Documentation Viewer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v4
      - name: Install dependencies
        run: poetry install
      - name: Run black
        run: poetry run black --check .
      - name: Run typechecker
        run: poetry run mypy src --ignore-missing-imports
      - name: Run linter
        run: poetry run pylint src

  build:
    runs-on: ubuntu-18.04
    needs: lint

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v4
      - name: Install dependencies
        run: poetry install
      - name: Run app
        run: poetry run python src/main.py ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gen
      - name: Copy to website
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.CI_PAT }}
          src_path: /.
          src_branch: gh-pages
          dst_path: /docs/reference/.
          dst_branch: main
          dst_owner: enso-org
          dst_repo_name: website
          clean: true
